name: CI

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Checkout Gradle Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/wrapper/dists/**/gradle*.zip
          key: windows-latest-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-windows-latest-

      - name: Build Debug
        run: ./gradlew build -x test
      - name: Build Release App
        run: |
          ./gradlew createDistributable
          ./gradlew packageExe

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributable-windows-latest
          if-no-files-found: ignore
          path: |
            build